import { Notice, PluginSettingTab, Setting, type App } from "obsidian";

import type ObsidianWorkbenchPlugin from "./main.js";
import { VaultPermissions } from "./permissions.js";
import { ALL_SCOPES, type PluginSettingsData } from "./settings-data.js";

function roots(value: string): string[] {
  return value
    .split(/[\n,]/)
    .map((item) => item.trim())
    .filter(Boolean);
}

export class WorkbenchSettingTab extends PluginSettingTab {
  readonly #plugin: ObsidianWorkbenchPlugin;

  constructor(app: App, plugin: ObsidianWorkbenchPlugin) {
    super(app, plugin);
    this.#plugin = plugin;
  }

  override display(): void {
    const { containerEl } = this;
    const settings = this.#plugin.settings;
    containerEl.empty();
    containerEl.addClass("obsidian-workbench-settings");
    containerEl.createEl("h2", { text: "Obsidian Workbench Companion" });

    const status = containerEl.createDiv({ cls: "obsidian-workbench-status" });
    status.dataset.state = this.#plugin.gatewayStatus.state;
    status.setText(
      this.#plugin.gatewayStatus.message === undefined
        ? `Gateway: ${this.#plugin.gatewayStatus.state}`
        : `Gateway: ${this.#plugin.gatewayStatus.state}. ${this.#plugin.gatewayStatus.message}`,
    );

    new Setting(containerEl)
      .setName("Gateway URL")
      .setDesc(
        "Secure outbound WebSocket endpoint. Only wss:// URLs are accepted.",
      )
      .addText((text) =>
        text
          .setPlaceholder("wss://gateway.example.com/device")
          .setValue(settings.gatewayUrl)
          .onChange(async (value) => {
            settings.gatewayUrl = value.trim();
            await this.#plugin.saveSettings();
          }),
      );

    new Setting(containerEl)
      .setName("Allowed roots")
      .setDesc(
        "Comma- or line-separated vault folders. Use . for the vault root.",
      )
      .addTextArea((text) =>
        text
          .setValue(settings.allowedRoots.join("\n"))
          .onChange(async (value) => {
            await this.#setRoots(
              settings,
              roots(value),
              settings.excludedRoots,
              "allowed",
            );
          }),
      );

    new Setting(containerEl)
      .setName("Excluded roots")
      .setDesc(
        "Denied subfolders. .obsidian is always denied and cannot be enabled.",
      )
      .addTextArea((text) =>
        text
          .setValue(settings.excludedRoots.join("\n"))
          .onChange(async (value) => {
            await this.#setRoots(
              settings,
              settings.allowedRoots,
              roots(value),
              "excluded",
            );
          }),
      );

    containerEl.createEl("h3", { text: "Permission scopes" });
    for (const scope of ALL_SCOPES) {
      new Setting(containerEl)
        .setName(scope)
        .setDesc(
          scope.endsWith(".read")
            ? "Allows this read capability."
            : "Allows this write capability.",
        )
        .addToggle((toggle) =>
          toggle
            .setValue(settings.enabledScopes.includes(scope))
            .onChange(async (enabled) => {
              settings.enabledScopes = enabled
                ? [...new Set([...settings.enabledScopes, scope])]
                : settings.enabledScopes.filter(
                    (candidate) => candidate !== scope,
                  );
              await this.#plugin.saveSettings();
            }),
        );
    }

    containerEl.createEl("h3", { text: "Pairing" });
    containerEl.createDiv({
      cls: "obsidian-workbench-warning",
      text: "The device token is stored in Obsidian plugin data for reconnects. Plugin data is not a hardware-backed secret store and may be included in backups or sync. The token is never displayed here.",
    });
    let pairingCode = "";
    new Setting(containerEl)
      .setName(
        settings.device === undefined
          ? "One-time pairing code"
          : "Paired device",
      )
      .setDesc(
        settings.device === undefined
          ? "Enter a short-lived code generated by the Workbench service."
          : `Paired ${new Date(settings.device.pairedAt).toLocaleString()} (device ending ${settings.device.deviceId.slice(-6)}).`,
      )
      .addText((text) => {
        text.setPlaceholder("XXXX-XXXX").onChange((value) => {
          pairingCode = value;
        });
        text.inputEl.type = "password";
        text.setDisabled(settings.device !== undefined);
      })
      .addButton((button) =>
        button
          .setButtonText("Pair")
          .setCta()
          .setDisabled(settings.device !== undefined)
          .onClick(async () => {
            button.setDisabled(true);
            try {
              await this.#plugin.pair(pairingCode);
              new Notice("Obsidian Workbench device paired.");
              this.display();
            } catch (error) {
              new Notice(
                error instanceof Error ? error.message : "Pairing failed.",
              );
              button.setDisabled(false);
            }
          }),
      );

    new Setting(containerEl)
      .setName("Connection")
      .setDesc(
        "Connect or disconnect this device without changing the paired token.",
      )
      .addToggle((toggle) =>
        toggle.setValue(settings.autoConnect).onChange(async (value) => {
          settings.autoConnect = value;
          await this.#plugin.saveSettings();
        }),
      )
      .addButton((button) =>
        button
          .setButtonText("Connect")
          .setDisabled(
            settings.device === undefined ||
              this.#plugin.gatewayStatus.state === "online",
          )
          .onClick(() => this.#plugin.connectGateway()),
      )
      .addButton((button) =>
        button
          .setButtonText("Disconnect")
          .setDisabled(this.#plugin.gatewayStatus.state === "offline")
          .onClick(() => this.#plugin.disconnectGateway()),
      );

    new Setting(containerEl)
      .setName("Revoke device")
      .setDesc(
        "Disconnect, request remote revocation, and always remove the local token.",
      )
      .addButton((button) =>
        button
          .setButtonText("Revoke")
          .setWarning()
          .setDisabled(settings.device === undefined)
          .onClick(async () => {
            button.setDisabled(true);
            try {
              await this.#plugin.revokeDevice();
              new Notice("Device revoked and local token removed.");
            } catch (error) {
              new Notice(
                `${error instanceof Error ? error.message : "Remote revocation failed."} The local token was removed.`,
              );
            }
            this.display();
          }),
      );

    new Setting(containerEl)
      .setName("Emergency disconnect")
      .setDesc(
        "Immediately closes the socket, cancels reconnects, and drops outbound events. No operation is queued.",
      )
      .addButton((button) =>
        button
          .setButtonText("Emergency disconnect")
          .setWarning()
          .onClick(() => {
            this.#plugin.emergencyDisconnect();
            new Notice("Emergency disconnect activated.");
            this.display();
          }),
      );

    containerEl.createEl("h3", { text: "Recent operations" });
    const table = containerEl.createEl("table", {
      cls: "obsidian-workbench-audit",
    });
    const header = table.createEl("thead").createEl("tr");
    for (const label of [
      "Time",
      "Method",
      "Target",
      "Result",
      "Duration",
      "Confirmed",
    ]) {
      header.createEl("th", { text: label });
    }
    const body = table.createEl("tbody");
    for (const entry of this.#plugin.audit.entries.slice(0, 20)) {
      const row = body.createEl("tr");
      row.createEl("td", { text: new Date(entry.timestamp).toLocaleString() });
      row.createEl("td", { text: entry.method });
      row.createEl("td", { text: entry.target || "-" });
      row.createEl("td", { text: entry.resultCode });
      row.createEl("td", { text: `${entry.durationMs} ms` });
      row.createEl("td", { text: entry.confirmationUsed ? "yes" : "no" });
    }
  }

  async #setRoots(
    settings: PluginSettingsData,
    allowedRoots: string[],
    excludedRoots: string[],
    changed: "allowed" | "excluded",
  ): Promise<void> {
    try {
      new VaultPermissions({
        allowedRoots,
        excludedRoots,
        scopes: settings.enabledScopes,
      });
      settings.allowedRoots = allowedRoots;
      settings.excludedRoots = excludedRoots;
      await this.#plugin.saveSettings();
    } catch (error) {
      new Notice(
        `${changed === "allowed" ? "Allowed" : "Excluded"} roots were not saved: ${
          error instanceof Error ? error.message : "invalid path policy"
        }`,
      );
    }
  }
}
